<?php

namespace Azure\Communication\Chat;

use Azure\Communication\Identity\Identity;
use Azure\Core\Model;

class MessageReadReceipt extends Model
{
    /** @var string Id of the chat message that has been read. This id is generated by the server. */
    public string $chatMessageId;

    /** @var \DateTime The time at which the message was read. The timestamp is in RFC3339 format: yyyy-MM-ddTHH:mm:ssZ. */
    public \DateTime $readOn;

    /** @var Identity Identifies a participant in Azure Communication services. */
    public Identity $senderCommunicationIdentifier;


    /**
     * {@inheritDoc}
     * @throws \Exception
     */
    public function __construct(array $config = [])
    {
        $config['readOn'] = $this->parseDateTime($config['readOn']);
        parent::__construct($config);
    }

    /**
     * Parses a rest response array into a MessageReadReceipt object.
     * @param array $messageReadReceipt
     * @return static
     * @throws \Exception
     */
    public static function fromArray(array $messageReadReceipt): static
    {
        return new static([
            'chatMessageId' => $messageReadReceipt['chatMessageId'],
            'readOn' => $messageReadReceipt['readOn'],
            'senderCommunicationIdentifier' => new Identity($messageReadReceipt['senderCommunicationIdentifier']['communicationUser']['id'])
        ]);
    }
}
